### ISSUE TITLE
:bug: fix(bal-nav): Navigation popup on tablet positioned under notifications

### ISSUE THREAD

**Issue by zsofia-oroszi-ibmix** [baloise/design-system#1782]
### Current Behavior

From tablet breakpoint, bal-nav doesn't have a z-index, therefore some elements are placed above the popup overlay. (e.g our notifications)

<img width="940" height="802" alt="Image" src="https://github.com/user-attachments/assets/c612e468-e02b-4076-b665-dd06858a3819" />

### Expected Behavior

On tablet the overlay should be positioned above the notifications, like on mobile viewports.

### Steps to Reproduce

open: https://www.baloise.ch/de/privatkunden.html
resize to tablet size
open main menu

### Version

19.5.0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by hirsch88** [comment]
Hi @zsofia-oroszi-ibmix 

This z-index is provided by IBM not use see screenshot.

<img width="421" height="199" alt="Image" src="https://github.com/user-attachments/assets/c63df3fc-29b1-4fb7-8698-4e685169e336" />

However, I fixed the z-index issue with the PR:
https://github.com/baloise/design-system/pull/1786

Created a snapshot version there, could you please verify if that works for the website?

Cheers
Gery

**Comment by zsofia-oroszi-ibmix** [comment]
Thanks @hirsch88, I tested the snapshot version, and it fixes the issue on the website.

**Comment by zsofia-oroszi-ibmix** [comment]
Hi @hirsch88, the z-index on the flyout works fine, but we still have an issue with the nav-meta-bar on the bottom inside bal-nav. Could you please apply the z-index there as well for tablet viewport?

<img width="826" height="811" alt="Image" src="https://github.com/user-attachments/assets/7c4dfb6b-1f6e-4a2e-a347-cf6023eea8fb" />
